# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param i the index of the node to call this on
#' @param c the current generation level.  0 = the first (i.e. the starting individual).
#' @param n the number of generations back to down.  1 means go no further than the offspring.
#' 2 means go no further than the grandkids.
#' @param P the pedigree structure
#' @param C a reference to a character vector to which sampled individuals' IDs will get
#' pushed on.  At the end, we can unique them.
NULL

#' @param i the index of the node to call this on
#' @param c the current generation level.  0 = the first (i.e. the sampled individual)
#' @param n the number of generations back to go.  1 means go no further than the parents.
#' 2 means go no further than the grandparents.
#' @param P the pedigree structure
#' @param C a reference to a character vector to which sampled individuals' IDs will get
#' pushed on.  At the end, we can unique them.
NULL

#' Function to make a vector of all the ancestors of an individual out to
#' n generations.  This is a replacement for the R implementation of
#' `ancestor_vectors()` which was too slow. This will get called
#' from with a C function in which the pedigree has been assembled.
#' @param sv vector of sample indexes
#' @param nv vector of names of all samples
#' @param Ped pedigree struct
#' @param n the number of generations.  0 = self, 1 = parent, 2 = grandparent, etc.
NULL

#' function being developed to test and use DFS stuff
#' @param L list of inputs
#' @param n the number of generations back to go when computing the ancestor vectors
#' and finding relatives.
#' @export
rcpp_ancestors_and_relatives <- function(L, n) {
    .Call('_CKMRpop_rcpp_ancestors_and_relatives', PACKAGE = 'CKMRpop', L, n)
}

#' stupid hello function
#'
#' yak yak
#' @export
rcpp_hello <- function() {
    .Call('_CKMRpop_rcpp_hello', PACKAGE = 'CKMRpop')
}

#' AReference testing
#'
#' Boing
#' @export
recursive_push_back <- function(Boing, i) {
    invisible(.Call('_CKMRpop_recursive_push_back', PACKAGE = 'CKMRpop', Boing, i))
}

#' A function used for quickly testing things
#'
#' Boing
#' @export
rcpp_test <- function(v1) {
    .Call('_CKMRpop_rcpp_test', PACKAGE = 'CKMRpop', v1)
}

